### ISSUE TITLE
Mirakurunの起動エラー

### ISSUE THREAD

**Issue by shiongu** [Chinachu/Mirakurun#11]
環境
CentOS Linux 7.2.1511
X64

mirakurun@2.0.0-rc.7
node -v　v6.9.1

事象
Mirakurunが　mirakurun startでOnlineにはなるものの
/var/run/mirakurun.sock　が生成されず
TCPポートも開かない。

 mirakurun-server x fork x online x 1 x 0%  x 8.6 MB

起動ログ
```
YAMLException: bad indentation of a sequence entry at line 2, column 2:
     types:
     ^
    at generateError (/usr/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/usr/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockSequence (/usr/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:932:7)
    at composeNode (/usr/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:1326:12)
    at readDocument (/usr/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:1489:3)
    at loadDocuments (/usr/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)
    at load (/usr/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:1562:19)
    at Object.safeLoad (/usr/lib/node_modules/mirakurun/node_modules/js-yaml/lib/js-yaml/loader.js:1580:10)
    at load (/source/Mirakurun/config.ts:108:17)
    at Object.loadTuners (/source/Mirakurun/config.ts:89:12)

```

**Comment by kanreisa** [comment]
YAML書式エラーです。インデントがおかしいです。
と、書かれてあるように、見えます。

**Comment by shiongu** [comment]
YAMLException: bad indentation of a sequence entry at line 2, column 2:
のエラーは　チューナー設定内で項目がダブっていたようでした。

そこから下のログは変わらずです。

**Comment by kanreisa** [comment]
設定は貼らないんですか　チューナーの

**Comment by shiongu** [comment]
現状のチューナー設定です。

```
- name: PT3-S1
 types:
 - BS
 - CS
 command: recpt1 --device /dev/pt3video0 <channel> - -
 decoder: arib-b25-stream-test
 isDisabled: false

- name: PT3-S2
 types:
 - BS
 - CS
 command: recpt1 --device /dev/pt3video1 <channel> - -
 decoder: arib-b25-stream-test
 isDisabled: false

- name: PT3-S3
 types:
 - BS
 - CS
 command: recpt1 --device /dev/pt3video4 <channel> - -
 decoder: arib-b25-stream-test
 isDisabled: false

- name: PT3-S4
 types:
 - BS
 - CS
 command: recpt1 --device /dev/pt3video5 <channel> - -
 decoder: arib-b25-stream-test
 isDisabled: false

- name: PT3-T1
 types:
 - GR
 command: recpt1 --device /dev/pt3video2 <channel> - -
 decoder: arib-b25-stream-test
 isDisabled: false

- name: PT3-T2
 types:
 - GR
 command: recpt1 --device /dev/pt3video3 <channel> - -
 decoder: arib-b25-stream-test
 isDisabled: false

- name: PT3-T3
 types:
 - GR
 command: recpt1 --device /dev/pt3video6 <channel> - -
 decoder: arib-b25-stream-test
 isDisabled: false

- name: PT3-T4
 types:
 - GR
 command: recpt1 --device /dev/pt3video7 <channel> - -
 decoder: arib-b25-stream-test
 isDisabled: false
```



チャンネル設定(最小限に設定してます)

```
- name: NHK総合
  type: GR
  channel: '24'

- name: NHK Eテレ
  type: GR
  channel: '13'
```
