### ISSUE TITLE
Mirakurun死なないでDVBチュナーをlockupさせる

### ISSUE THREAD

**Issue by Corsaire01** [Chinachu/Mirakurun#24]
### Environment
* Version of Mirakurun: `latest from git`
* Version of Node: `v6.5.0`
* Version of NPM: `3.10.3`
* Platform: 
* Architecture: x64

### Issue
PT3チュナーがlockupされて、強制的にPCを再起動やらないとダメな状態になりました。
これは最近なことです、mirakurunを更新した後のことです。
having my PT3 card getting locking up, I have to make a forced reboot.
This is a recent situation, started to happen afer a mirakurun update.

問題はrecpt1のプロセスが起動しすぎて、やがてPT3カードがlockupすることになりそうです。
Problem is triggered by too much recpt1 processes getting started making the PT3 card lock up.

まず気になるのは同時にmirakurunプロセスが二つがあって、「sudo murakurun stop」を実行しても一つが残る：
First I'm intrigued by having two mirakurun processes running simultaneously, even after issuing a "sudo mirakurun stop" one is still left.

起動状態
At system boot up
```
chinachu@goelette:~$ ps auwx | grep -i miraku
root       952 55.8  4.8 995800 99100 ?        S<sl 22:48   1:26 Mirakurun: Server
root       976 34.0  3.6 978252 75280 ?        S<sl 22:48   0:51 Mirakurun: Server

chinachu@goelette:~$ ps auwx | grep -i recpt
root      1432  3.5  0.1  38608  2252 ?        S<l  22:49   0:03 recpt1 --device /dev/pt3video1 --lnb 15 BS15_0 - -

chinachu@goelette:~$ pstree -halup
systemd,1 noplymouth
  ├─PM2 v2.6.1: God,935
  │   ├─Mirakurun: Serv,976
  │   │   ├─{V8 WorkerThread},978
  │   │   ├─{V8 WorkerThread},979
  │   │   ├─{V8 WorkerThread},980
  │   │   ├─{V8 WorkerThread},981
  │   │   ├─{node},977
  │   │   ├─{node},1037
  │   │   ├─{node},1038
  │   │   ├─{node},1039
  │   │   └─{node},1040
  │   ├─node /home/chin,982,chinachu
  │   │   ├─{V8 WorkerThread},984
  │   │   ├─{V8 WorkerThread},985
  │   │   ├─{V8 WorkerThread},986
  │   │   ├─{V8 WorkerThread},987
  │   │   ├─{node},983
  │   │   ├─{node},1061
  │   │   ├─{node},1062
  │   │   ├─{node},1063
  │   │   └─{node},1064
  │   ├─node /home/chin,990,chinachu
  │   │   ├─{V8 WorkerThread},992
  │   │   ├─{V8 WorkerThread},993
  │   │   ├─{V8 WorkerThread},994
  │   │   ├─{V8 WorkerThread},995
  │   │   ├─{node},991
  │   │   ├─{node},1065
  │   │   ├─{node},1066
  │   │   ├─{node},1067
  │   │   └─{node},1068
  │   ├─{PM2 v2.6.1: God},972
  │   ├─{PM2 v2.6.1: God},973
  │   ├─{PM2 v2.6.1: God},974
  │   ├─{PM2 v2.6.1: God},975
  │   ├─{V8 WorkerThread},937
  │   ├─{V8 WorkerThread},938
  │   ├─{V8 WorkerThread},939
  │   ├─{V8 WorkerThread},940
  │   └─{node},936
  ├─node,848 /usr/local/lib/node_modules/pm2/bin/pm2 resurrect --no-daemon
  │   ├─Mirakurun: Serv,952
  │   │   ├─recpt1,1432 --device /dev/pt3video1 --lnb 15 BS15_0 - -
  │   │   │   ├─{recpt1},1437
  │   │   │   ├─{recpt1},1438
  │   │   │   └─{recpt1},1439
  │   │   ├─{V8 WorkerThread},954
  │   │   ├─{V8 WorkerThread},955
  │   │   ├─{V8 WorkerThread},956
  │   │   ├─{V8 WorkerThread},957
  │   │   ├─{node},953
  │   │   ├─{node},962
  │   │   ├─{node},963
  │   │   ├─{node},964
  │   │   └─{node},965
  │   ├─{V8 WorkerThread},865
  │   ├─{V8 WorkerThread},866
  │   ├─{V8 WorkerThread},867
  │   ├─{V8 WorkerThread},868
  │   ├─{node},863
  │   ├─{node},948
  │   ├─{node},949
  │   ├─{node},950
  │   └─{node},951
 ├─chinachu,903,chinachu /home/chinachu/Chinachu-gamma/chinachu service wui execute
  │   ├─node,916 app-wui.js
  │   │   ├─{V8 WorkerThread},922
  │   │   ├─{V8 WorkerThread},923
  │   │   ├─{V8 WorkerThread},924
  │   │   ├─{V8 WorkerThread},925
  │   │   ├─{node},921
  │   │   ├─{node},968
  │   │   ├─{node},969
  │   │   ├─{node},970
  │   │   └─{node},971
  │   └─tee,917 -a ./log/wui
  ├─chinachu,904,chinachu /home/chinachu/Chinachu-gamma/chinachu service operator execute
  │   ├─node,919 app-operator.js
  │   │   ├─{V8 WorkerThread},927
  │   │   ├─{V8 WorkerThread},928
  │   │   ├─{V8 WorkerThread},929
  │   │   ├─{V8 WorkerThread},930
  │   │   ├─{node},926
  │   │   ├─{node},944
  │   │   ├─{node},945
  │   │   ├─{node},946
  │   │   └─{node},947
  │   └─tee,920 -a ./log/operator
```

mirakurunをstopしようとしたら
After issuing a stop command to mirakurun
```
chinachu@goelette:~$ sudo mirakurun stop

chinachu@goelette:~$ sudo pm2 status
┌───────────────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────────┬──────┬──────────┐
│ App name          │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem        │ user │ watching │
├───────────────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────────┼──────┼──────────┤
│ chinachu-operator │ 2  │ fork │ 990 │ online  │ 0       │ 5m     │ 0%  │ 38.1 MB    │ root │ disabled │
│ chinachu-wui      │ 1  │ fork │ 982 │ online  │ 0       │ 5m     │ 0%  │ 124.0 MB   │ root │ disabled │
│ mirakurun-server  │ 0  │ fork │ 0   │ stopped │ 0       │ 0      │ 0%  │ 0 B        │ root │ disabled │
└───────────────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

chinachu@goelette:~$ ps auwx | grep -i recpt
root      3292  5.1  0.1  38912  2480 ?        S<l  22:52   0:05 recpt1 --device /dev/pt3video0 --lnb 15 CS4 - -

chinachu@goelette:~$ ps auwx | grep -i miraku
root       952 59.0  7.6 1025196 155940 ?      S<sl 22:48   3:35 Mirakurun: Server

chinachu@goelette:~$ pstree -halup
systemd,1 noplymouth
  ├─node,848 /usr/local/lib/node_modules/pm2/bin/pm2 resurrect --no-daemon
  │   ├─Mirakurun: Serv,952
  │   │   ├─recpt1,3292 --device /dev/pt3video0 --lnb 15 CS4 - -
  │   │   │   ├─{recpt1},3297
  │   │   │   ├─{recpt1},3298
  │   │   │   └─{recpt1},3299
  │   │   ├─recpt1,3799 --device /dev/pt3video2 16 - -
  │   │   ├─{V8 WorkerThread},954
  │   │   ├─{V8 WorkerThread},955
  │   │   ├─{V8 WorkerThread},956
  │   │   ├─{V8 WorkerThread},957
  │   │   ├─{node},953
  │   │   ├─{node},962
  │   │   ├─{node},963
  │   │   ├─{node},964
  │   │   └─{node},965
  │   ├─{V8 WorkerThread},865
  │   ├─{V8 WorkerThread},866
  │   ├─{V8 WorkerThread},867
  │   ├─{V8 WorkerThread},868
  │   ├─{node},863
  │   ├─{node},948
  │   ├─{node},949
  │   ├─{node},950
  │   └─{node},951
```

mirakurunとrecpt1プロセスは永久に残っている。
どこかに二重の起動が行われている。
There are mirakurun and recpt1 processes running continuously. 
Somewhere, processes are started twice.

どこに調査すればいいでしょう？
Where should I look up ?

**Comment by kanreisa** [comment]
please write in English.

**Comment by Corsaire01** [comment]
I added the English version

**Comment by kanreisa** [comment]
try below: (note: configurations are kept)
```sh
sudo -i
npm uninstall -g --unsafe mirakurun
pm2 unstartup
pm2 update
reboot
```
```sh
sudo -i
npm install -g --unsafe mirakurun
reboot
```
```sh
sudo -i
ps aux | grep PM2
pm2 status
```

* please tell me your platform which you're running
https://github.com/Chinachu/Mirakurun/blob/master/.github/CONTRIBUTING.md#report-an-issue

* please paste the server/tuners configuration

**Comment by Corsaire01** [comment]
```
chinachu@goelette:~$ uname -a
Linux goelette 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

chinachu@goelette:~$ cat /etc/debian_version
stretch/sid
```

"/usr/local/etc/mirakurun/tuners.yml"
```
- name: PT3-S1
  types:
    - BS
    - CS
  command: recpt1 --device /dev/pt3video0 --lnb 15 <channel> - -
  decoder: arib-b25-stream-test
  isDisabled: false

- name: PT3-S2
  types:
    - BS
    - CS
  command: recpt1 --device /dev/pt3video1 --lnb 15 <channel> - -
  decoder: arib-b25-stream-test
  isDisabled: false

- name: PT3-T1
  types:
    - GR
  command: recpt1 --device /dev/pt3video2 <channel> - -
  decoder: arib-b25-stream-test
  isDisabled: false

- name: PT3-T2
  types:
    - GR
  command: recpt1 --device /dev/pt3video3 <channel> - -
  decoder: arib-b25-stream-test
  isDisabled: false

- name: TBS6922
  types:
    - SKY
  command: szap-s2j -c /usr/local/etc/szap-s2j.conf -l <satelite> -S 1 -p -r -M 5 -C 35 <channel>
  dvbDevicePath: /dev/dvb/adapter0/dvr0
  decoder: arib-b1-stream-test
  isDisabled: true
```
