### ISSUE TITLE
【報告】channels.yml変更後に視聴できなくなった

### ISSUE THREAD

**Issue by cuckoozero** [Chinachu/Mirakurun#35]
### Environment
* Version of Mirakurun: `2.7.0`
* Version of Node: `v8.10.0`
* Version of NPM: `6.0.0`
* Platform: Windows10 home
* Architecture: x64

### Issue
たびたびお世話になります。

Windows環境で利用させていただいており、先日のBSプレミアムのトランスポンダ変更に伴い、BonRecTestおよびMirakurunのチャンネル設定を変更する必要がありましたが、その後EPGStationからの試聴・録画ができなくなりました。（TVTestからはチャンネルスキャンをすることで視聴できています）

services.jsonを見るとchannels.yml変更後の内容が反映されていなかったので、services.jsonとprograms.jsonを削除の上Mirakurunを再起動したところ、正常に視聴できるようになりました。

そもそも仕様としてそうなのか、あるいはバグなのかはわかりませんでしたが、念のため報告します。

**Comment by advancedbear** [comment]
### Environment
- Version of Mirakurun: 2.7.0
- Version of Node: v8.9.4
- Version of NPM: 5.6.0
- Platform: Windows Server 2016 Essentials
- Architecture: x64
----
当方でも同様の問題が、地上デジタル放送のチャンネルにて起きていました。
今月初頭に東京→名古屋の引っ越しを行いましたが、その際にMirakurunのchannels.ymlを修正しただけの状態でMirakurunを再起動すると、チャンネル名についてはyamlの記述に準拠したものになりますが、サービスIDが「前地域での同チャンネル番号で利用されていたチャンネルのサービス」が残ったままになり更新されません。
````yaml
{
  "type": "GR",
  "channel": "14",
  "name": "三重テレビ",
  "services": [
    {
      "id": 3273601024,
      "serviceId": 1024,
      "networkId": 32736,
      "name": "ＮＨＫ総合１・東京"
    },
    {
      "id": 3273601025,
      "serviceId": 1025,
      "networkId": 32736,
      "name": "ＮＨＫ総合２・東京"
    },
    {
      "id": 3273601408,
      "serviceId": 1408,
      "networkId": 32736,
      "name": "ＮＨＫ携帯Ｇ・東京"
    }
  ]
},
````
services.jsonとprograms.jsonを削除してMirakurunを再起動すると、両ファイルが再生成されチャンネルのサービスIDも正しいものに変わりました。
````yaml
{
  "type": "GR",
  "channel": "14",
  "name": "三重テレビ",
  "services": [
    {
      "id": 3215038960,
      "serviceId": 38960,
      "networkId": 32150,
      "name": "三重テレビ１"
    },
    {
      "id": 3215038961,
      "serviceId": 38961,
      "networkId": 32150,
      "name": "三重テレビ２"
    },
    {
      "id": 3215039344,
      "serviceId": 39344,
      "networkId": 32150,
      "name": "三重テレビ携帯"
    }
  ]
},
````
channels.ymlの変更をイベントに、programs.jsonやservices.jsonの再構築がされても良いのではないかなと感じますが如何お考えでしょうか。
