### ISSUE TITLE
Request to add <frequency> and <polarity> options to channels.yml for DVB-S2 (SKY) channels

### ISSUE THREAD

**Issue by trollcop** [Chinachu/Mirakurun#77]
### Issue

Currently there is no easy way to synchronize DVB-S2 tuning with data in channels.yml. Need to maintain zap.conf with redundant data for tuning.

### Suggestion

- Add `frequency: xxxxx` to channel specification. This will be passed to command as `<frequency>`
- Add `polarity: <H> or <V>`  to channel specification. This will be passed to command as `<polarity>`

The above would result in a command line for example:

```
--freq 12598 --satellite JCSAT4B --polarity H
```

and tuners.yml would have something like

```
recapp --freq <frequency> --satellite <satelite> --polarity <polarity>
```

Which means immediate tuning can be done (freq, polarity, tone are known).
Complete channels.yml would look something like this:

```
- name: AT-X
  type: SKY
  channel: CH667
  freq: 12718
  polarity: V
  serviceId: 33435
  satelite: JCSAT3A
```

Also, "satellite" has two `ll`.

Please consider it.

**Comment by kanreisa** [comment]
Thank you.
added on a192dcd.

**Comment by trollcop** [comment]
Thanks!

I've added the parameters to my recskapa fork to match these new capabilities: https://github.com/trollcop/recskapa/commit/3c53ea7297a14bd3a3f5c59dc243c75f70e6d9a6

Now its possible to tune without using skapa.conf, and specifying all tuning details inside channels.yml

**Comment by trollcop** [comment]
I recently upgraded my chinachu to latest version and confirmed this patch working, thanks a lot.

[channels.txt](https://github.com/Chinachu/Mirakurun/files/6218800/channels.txt)

Here's an example of skapa channels.yml (attached .txt file) and tuners.yml

```
- name: TBS6903(A)
  types:
    - SKY
  command: recskapa -a 0 -l <satellite> -b -s --freq <freq> --pol <polarity> - -

- name: TBS6903(B)
  types:
    - SKY
  command: recskapa -a 1 -l <satellite> -b -s --freq <freq> --pol <polarity> - -
```
